name: Ruff 

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry 
      - name: Install required Python packages
        run: poetry install
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: chartboost/ruff-action@v1
        name: Lint using ruff
        with:
          args: 'check'
      - uses: chartboost/ruff-action@v1
        name: Format using ruff
        with:
          args: 'format --diff'
      - name: Unit Tests
        run: poetry run pytest test_test.py --doctest-modules --cov --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html

